# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl_poc', '0002_auto_20170718_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
